#!/usr/bin/env bash
## This script will be transferig a file from our client to a server
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
path_file="$1"
ip="$2"
username="$3"
ssh_path="$4"
scp -o StrictHostKeyChecking=no -i "$ssh_path" "$path_file" "$username@$ip":~/
