#!/usr/bin/env bash
## This is a script which installs a new server called nginx configures it and returns a certain string hello world !
echo -e "Updating and installing nginx\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y
echo -e "\n Setting uo some small stuff\n"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www
cp /var/www/index.nginx-debian.html /var/www/index.nginx-debian.html.bckp
echo -e "Hello World" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
echo -e "\n Installation complete,go to your browser to confirm if its working\n"
