#!/usr/bin/env bash
## This is a script which installs a new server called nginx configures it and returns a certain string hello world !
echo -e "Updating and installing nginx\n"
apt-get update -y
apt-get install nginx -y
echo -e "\n Setting uo some small stuff\n"
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Restarting Nginx..."
service nginx restart
echo "Installation complete,go to your browser to confirm if its working"
