#!/usr/bin/env bash
## in this task im writting a script which configures itself to be identical to anoter server web-o1
apt-get update
apt-get install -y nginx
custom_header_value=$(hostname)
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        proxy_pass http://127.0.0.1:80;
        proxy_set_header X-Served-By $custom_header_value; # Custom header configuration
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}" > /etc/nginx/sites-available/default
systemctl restart nginx
