#!/usr/bin/env bash
#This script will print bad luc from china when i=4, bad luck from japan when i=9 and bad luck from italy when i=17

word1="bad luck from China"
word2="bad luck from Japan"
word3="bad luck from Italy"
i=1

while ((i<=20)); do
case "$i" in 4)
echo "$i"
echo "$word1"
;;
9)
echo "$i"
echo "$word2"
;;
17)
echo "$i"
echo "$word3"
;;
*)
echo "$i"
;;
esac
((i++))
done
