#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using a while loop

hours=0

while ((hours <= 12)); do
    minutes=1

    while ((minutes <= 59)); do
        echo "Hour: $hours"
        printf "%02d\n" "$minutes"
        ((minutes++))
    done

    ((hours++))
done

