#!/usr/bin/env bash
## This script will be creating an rsa key pair with a name school and bits should be 4096 the paraphrase being betty
private_key="school."
no_of_bits=4096
paraphrase="betty"
ssh-keygen -t rsa -b "$no_of_bits" -f "$private_key" -N "$passphrase"
echo "RSA key pair generated successfully."
